openapi: 3.0.0
info:
  title: IDMA-RCM Credentials API
  description: IDMA Service für die Generierung und Abfrage der Credentials
  version: 0.0.1
servers:
  - url: http://localhost:8080/idma-war/service/rcm
    description: Lokaler Testserver
paths:
  /credentials/{toNr}/{ask}:
    put:
      summary: Credentials generieren
      parameters:
      - in: path
        name: toNr
        required: true
        schema:
          type: string
          pattern: '^\\d{5,12}$'
          example: '550012345678'
        description: TONR des Subscribers
      - in: path
        name: ask
        required: true
        schema:
          type: integer
          minimum: 0
          maximum: 1
          example: 1
        description: Anschlusskennung mitgenerieren
      responses:
        '200':
          description: Antwort Struktur für erfolgreiche Aufrufe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
        '500':
          description: Antwort Struktur für fehlerhafte Aufrufe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialsError'
  /credentials/{toNr}:
    get:
      summary: Credentials abfragen
      parameters:
      - in: path
        name: toNr
        required: true
        schema:
          type: string
          pattern: '^\\d{5,12}$'
          example: '550012345678'
        description: TONR des Subscribers
      responses:
        '200':
          description: Antwort Struktur für erfolgreiche Aufrufe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
        '500':
          description: Antwort Struktur für fehlerhafte Aufrufe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialsError'
components:
  schemas:
    Credentials:
      type: object
      properties:
        anschlusskennung:
          type: string
          description: Anschlusskennung (verschlüsselt)
          example: 'v69Ih1owMoRUpAG+63ew6XUHu0cqynbx'
        passwort:
          type: string
          description: Passwort (verschlüsselt)
          example: 'Je4ExJ7CD5eoZ95tkbwF3JPHN2/t4RiD'
        probewort:
          type: string
          description: Probewort (verschlüsselt)
          example: '7XJ0stxRRimGDjD5nkATwAmaddtaNd9P'
      required:
      - passwort
      - probewort
    CredentialsError:
      type: object
      properties:
        returnCode:
          type: integer
          description: Fehlercode
          example: 10
        returnText:
          type: string
          description: Fehlertext
          example: 'Invalide toNr'
      required:
      - returnCode